server:
  port: 8080
  servlet:
    context-path: / # 如果你部署在Thunder平台走流水线，建议配置 ${SERVER_CONTEXT_PATH}
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/moving?useSSL=false&useUnicode=true&characterEncoding=utf-8&rewriteBatchedStatements=true&allowMultiQueries=true&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root #your username
    password: 123456 #your password
  redis:
    port: 6379 #your redis
    host: 127.0.0.1 #your redis
    ssl: false
custom:
  login:
    okta:
      client-id: 0oa274u4ixclGMr3g0h8
      client-secret: fuoe6FhwQYVeTY4hMePUgFMnxS0eDK-bq4aZuWrX6_SoQ80Bflfm1leM0QHOWLL6
      authorization-endpoint: https://login-test.envision-sso.com/oauth2/default/v1/authorize
      token-endpoint: https://login-test.envision-sso.com/oauth2/default/v1/token
      userinfo-endpoint: https://login-test.envision-sso.com/oauth2/default/v1/userinfo
      redirect-uri: http://localhost:8080/login/okta/auth
      scope: openid
    wecom:
      app-id: wx67d6b0d5c9512363
      agent-id: 1000115
      client-secret: viVw_dH273J3E4gONexDI0ikiUHwCaL3TMGdvJugXgc
      userinfo-endpoint: https://plt-envisioncn.c-dev-ty.envision-io.com/apis/it/wx/apis/auth/userinfo?code={code}&secret={secret}&corp=1
      authorization-endpoint: https://open.weixin.qq.com/connect/oauth2/authorize
      redirect-uri: https://plt.envisioncn.dev.pe2.cc/apps/hr/socialrecruit/mobile/sys/wechatqiye/qiyewechat_redirect
      scope: snsapi_userinfo
    aad:
      client-id: ff0d9b66-2979-4529-beb0-21cdf6ebf6b4
      client-secret: NZS8Q~UiEx6.cf8hRcCELJEa1BfYMCKdk1XHzcV-
      tenant-id: 20e8dfa9-4087-428e-865a-329bac3297da
      authorization-endpoint: https://login.microsoftonline.com/${custom.login.aad.tenant-id}/oauth2/v2.0/authorize
      token-endpoint: https://login.microsoftonline.com/${custom.login.aad.tenant-id}/oauth2/v2.0/token
      userinfo-endpoint: https://graph.microsoft.com/oidc/userinfo
      redirect-uri: http://localhost:8080/login/aad/auth
      scope: openid profile email https://graph.microsoft.com/User.Read
  platform:
    token:
      app-id: 8EE12F20CB2B46978E97078D356D60E2
      grant-type: CREDENTIAL
#      app-secret: GQE%sj=kS0*ws5091P!w
      app-secret: ^&#:Y40v8Q4JAV8G0!6?
      domain: https://platform.envision-io.com
      user-id: SYS10552
      app-name: it-gdm
  whitelist:
    sms: 17051066161,18616805231
    email: jingjing.dong@envision-energy.com
    wecom: 59930
  crypto:
    secret-key: abcdefghijklmnopqrstuvwxyz1234567890
