drop table if exists sys_user;
CREATE TABLE if not EXISTS `sys_user` (
    `id` bigint unsigned NOT NULL COMMENT 'ID',
    `username` varchar(100)  NOT NULL COMMENT '用户名,张三(san.zhang)',
    `user_code` varchar(50)  NOT NULL COMMENT '用户编号',
    `account` varchar(50)  NOT NULL COMMENT '域账号',
    `avatar` varchar(100)  NOT NULL COMMENT '头像',
    `search_str` varchar(200)  NOT NULL COMMENT '员⼯号、域账号、拼⾳、汉字拼接⽽成',
    `dept_code` varchar(50)  NOT NULL COMMENT '部门编号',
    `dept_name` varchar(50)  NOT NULL COMMENT '部门名称',
    `division_code` varchar(50)  NOT NULL COMMENT '体系编号',
    `division_name` varchar(50)  NOT NULL COMMENT '体系名称',
    `locale` varchar(50)  NOT NULL DEFAULT 'zh_CN' COMMENT '用户默认语言',
    `is_in_service` boolean NOT NULL DEFAULT true COMMENT '是否在职，0代表否(离职)，非0值代表是(在职)',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `create_by` varchar(100)  NOT NULL DEFAULT '' COMMENT '创建人工号',
    `create_by_name` varchar(100)  NOT NULL DEFAULT '' COMMENT '创建人姓名',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '修改时间',
    `update_by` varchar(100)  NOT NULL DEFAULT '' COMMENT '修改人工号',
    `update_by_name` varchar(100)  NOT NULL DEFAULT '' COMMENT '修改人姓名',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_user_code` (`user_code`),
    KEY `idx_in_service` (`is_in_service`),
    KEY `idx_division_code` (`division_code`),
    KEY `idx_dept_code` (`dept_code`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='系统用户表';